version: '3.9'

services:

  api:
    build:
      context: ../
      dockerfile: .devops/Dockerfile
    container_name: festeroapp-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=FESTEROAPP;User Id=sa;Password=festeroapp2025!@$#;TrustServerCertificate=True;
    networks:
      - festeroapp-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: festeroapp-sql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=festeroapp2025!@$#
    networks:
      - festeroapp-network

networks:
  festeroapp-network:
    driver: bridge
